# Generated by Django 3.1.5 on 2021-01-27 08:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210127_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.get_image_filename, verbose_name='Image1'),
        ),
    ]
