# Generated by Django 3.1.5 on 2021-01-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200718_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='done',
        ),
    ]
